// Jpeg.java
//
// SPDX-FileCopyrightText: 2024 Element Davv <elementdavv@hotmail.com>
//
// SPDX-License-Identifier: BSD-3-Clause

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.timelegend.pdf.crl;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
